services:
  - type: web
    name: achados-onco-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard_onco_render.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
